parameters:


services:

    aw.widget.header:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }
            - { name: aw.widget.whitelabel }

    aw.widget.footer:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }
            - { name: aw.widget.whitelabel }

    aw.widget.left_top:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.credit_card_tools_zone:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.left_bottom:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.accounts:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.accounts_list:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.bookings:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.trips:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.onecard:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.default:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }

    aw.widget.business_header:
        class: AwardWallet\WidgetBundle\Widget\ZoneWidget
        parent: aw.widget_abstract
        tags:
            - { name: aw.widget_container }
            - { name: aw.widget.whitelabel }

    aw.widget.contact_us:
            class: AwardWallet\WidgetBundle\Widget\ZoneWidget
            parent: aw.widget_abstract
            tags:
                - { name: aw.widget_container }

    aw.widget.user_profile:
                class: AwardWallet\WidgetBundle\Widget\ZoneWidget
                parent: aw.widget_abstract
                tags:
                    - { name: aw.widget_container }

    aw.widget.connections:
                class: AwardWallet\WidgetBundle\Widget\ZoneWidget
                parent: aw.widget_abstract
                tags:
                    - { name: aw.widget_container }

    aw.widget.connections_edit:
                class: AwardWallet\WidgetBundle\Widget\ZoneWidget
                parent: aw.widget_abstract
                tags:
                    - { name: aw.widget_container }