elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
  environment:
      - VIRTUAL_PORT=9200
      - VIRTUAL_HOST=elastic.awardwallet.docker
  networks:
    default:
      aliases:
        - stat-es.awardwallet.com
        - local.log.awardwallet.com
kibana:
  image: docker.elastic.co/kibana/kibana:6.4.0
  environment:
      - VIRTUAL_PORT=5601
      - VIRTUAL_HOST=kibana.awardwallet.docker
fluent:
  image: docker.awardwallet.com/service/fluent
