version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      - SERVER_NAME=kibana.docker
      - VIRTUAL_HOST=kibana.docker
      - HTTPS_METHOD=noredirect
      - HSTS_MAX_AGE=1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
