version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - "xpack.security.enabled=false"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    links:
      - elasticsearch:elasticsearch
    ports:
      - "80:5601"
    restart: always

volumes:
  es-data: {}
